name: Update Assistant Index

on:
  push:
    branches:
      - main
    paths:
      - 'assistants/**/*.yml'
      - 'update_assistant_index.py'
      - 'README.md'

jobs:
  update-index:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
    
    - name: Update index
      run: python update_assistant_index.py
    
    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add README.md
        git commit -m "Update assistant index" || echo "No changes to commit"
        git push