name: Update Assistant Stats

on:
  push:
    paths:
      - 'assistants/**/*.yml'
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  update-stats:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for accurate stats
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
    
    - name: Update assistant stats
      run: python scripts/update_stats.py
    
    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add assistant-counts.json README.md
        git commit -m "Update assistant stats" || echo "No changes to commit"
        git push